# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and export the IPA file"
  lane :build_ipa do
    build_app(
      workspace: "loginregistercrm.xcworkspace", # Replace with your workspace name if different
      scheme: "loginregistercrm",                # Replace with your scheme name if different
      export_method: "ad-hoc"   ,
      export_options: {
        provisioningProfiles: {
          "com.cygnisoft.loginregistercrm" => "Cygnisoft-ATS"
        }
      }
                       # or "app-store", "development", "enterprise"
    )
  end
end